--USUWANIE TABEL:
DROP TABLE PRODUKT CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCENT CASCADE CONSTRAINTS PURGE;
DROP TABLE PRACOWNIK CASCADE CONSTRAINTS PURGE;
DROP TABLE KLIENT CASCADE CONSTRAINTS PURGE;
DROP TABLE ART_SYPKIE CASCADE CONSTRAINTS PURGE;
DROP TABLE PRZYPRAWY CASCADE CONSTRAINTS PURGE;
DROP TABLE OLEJE CASCADE CONSTRAINTS PURGE;
DROP TABLE PRZETWORY_SOSY CASCADE CONSTRAINTS PURGE;
DROP TABLE MAKARONY CASCADE CONSTRAINTS PURGE;
DROP TABLE ART_MLECZNE CASCADE CONSTRAINTS PURGE;
DROP TABLE SLODYCZE CASCADE CONSTRAINTS PURGE;
DROP TABLE NAPOJE CASCADE CONSTRAINTS PURGE;
DROP TABLE HERBATY_KAWY CASCADE CONSTRAINTS PURGE;
DROP TABLE FAKTURA CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMOCHOD CASCADE CONSTRAINTS PURGE;
DROP TABLE DANE_PRACOWNIKA CASCADE CONSTRAINTS PURGE;
DROP TABLE DANE_FAKTURY CASCADE CONSTRAINTS PURGE;
--USUWANIE TABEL LOGÓW:
DROP TABLE FAKTURA_LOG CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMOCHOD_LOG CASCADE CONSTRAINTS PURGE;
DROP TABLE KLIENT_LOG CASCADE CONSTRAINTS PURGE;
--USUWANIE SEKWENCJI:
DROP SEQUENCE PRODUKT_SEQ;
DROP SEQUENCE PRODUCENT_SEQ;
DROP SEQUENCE PRACOWNIK_SEQ;
DROP SEQUENCE KLIENT_SEQ;
DROP SEQUENCE FAKTURA_SEQ;
DROP SEQUENCE DANE_FAKTURY_SEQ;
DROP SEQUENCE SAMOCHOD_SEQ;
DROP SEQUENCE DANE_PRACOWNIKA_SEQ;
DROP SEQUENCE NR_UMOWY_SEQ;
--USUWANIE SEKWENCJI DO TABEL WYZWALACZY:
DROP SEQUENCE FAKTURA_LOG_SEQ;
DROP SEQUENCE SAMOCHOD_LOG_SEQ;
DROP SEQUENCE KLIENT_LOG_SEQ;
--USUWANIE PROCEDUR I FUNKCJI:
DROP PROCEDURE DODAJ_DO_FAKTUR;
DROP PROCEDURE LICZ_BRUTTO_NA_FAKTURZE;
DROP PROCEDURE PODLICZENIE_OKRESOWE;
DROP PROCEDURE PODWYZKA_PRACOWNIKOW;
DROP PROCEDURE OBLICZANIE_BRUTTO_VAT;
--USUWANIE WIDOKOW:
DROP VIEW WARTOSCI_FAKTUR;
DROP VIEW KLIENT_FAKTURA;
DROP VIEW SAMOCHOD_PRACOWNIK
--USUWANIE WYZWALACZY:
DROP TRIGGER LOGI_FAKTURA;
DROP TRIGGER LOGI_SAMOCHOD;
DROP TRIGGER LOGI_KLIENT;
--CZYSZCZENIE KOSZA:
PURGE RECYCLEBIN;