SET ECHO ON
DROP PROCEDURE DODAJ_DO_FAKTUR;
DROP PROCEDURE LICZ_BRUTTO_NA_FAKTURZE;
DROP PROCEDURE PODLICZENIE_OKRESOWE;
DROP PROCEDURE PODWYZKA_PRACOWNIKOW;
DROP PROCEDURE OBLICZANIE_BRUTTO_VAT;
SET ECHO OFF