$CLS
PROMPT Menu:
PROMPT 1. LICZ_BRUTTO_NA_FAKTURZE
PROMPT 2. PODLICZENIE_OKRESOWE
PROMPT 3. PODWYZKA_PRACOWNIKOW
PROMPT 4. OBLICZANIE_BRUTTO_VAT
PROMPT 5. ZMIANA_CEN_TOWAROW
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT 'WYBIERZ NR OPCJI OD 1 DO 5: '
$CLS
DEFINE CURR_DIR='&1'
PROMPT wybor = &wybor
@'&CURR_DIR/&wybor.SQL'
PAUSE
@main.sql