SET ECHO ON
CREATE TABLE PRODUKT(
  ID NUMBER(6) PRIMARY KEY,
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(6,2),
  CENA_BRUTTO  NUMBER(6,2)
);

CREATE TABLE PRODUCENT(
  ID          NUMBER(6) PRIMARY KEY,
  NAZWA       VARCHAR2(50 CHAR),
  NIP         NUMBER(10) NOT NULL,
  ULICA       VARCHAR2(50 CHAR),
  NR_BUDYNKU  NUMBER(5),
  NR_LOKALU   NUMBER(5),
  KOD         VARCHAR2(6 CHAR),
  POCZTA      VARCHAR2(50 CHAR)
);

CREATE TABLE PRACOWNIK(
  ID            NUMBER(6) PRIMARY KEY,
  IMIE          VARCHAR2(20 CHAR),
  NAZWISKO      VARCHAR2(50 CHAR),
  ULICA         VARCHAR2(50 CHAR),
  NR_DOMU       NUMBER(4),
  NR_MIESZKANIA NUMBER(4),
  KOD           VARCHAR2(6 CHAR),
  POCZTA        VARCHAR2(50 CHAR),
  NR_TELEFONU   NUMBER(9)
);

CREATE TABLE KLIENT(
  ID            NUMBER(6) PRIMARY KEY,
  NAZWA         VARCHAR2(120 CHAR),
  NIP           NUMBER(10),
  ULICA         VARCHAR2(50 CHAR),
  NR_DOMU       NUMBER(4),
  NR_MIESZKANIA NUMBER(4),
  KOD           VARCHAR2(6 CHAR),
  POCZTA        VARCHAR2(50 CHAR),
  NR_TELEFONU   NUMBER(9)
); 

--TABELE Z KLUCZAMI OBCYMI:

CREATE TABLE ART_SYPKIE(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_ART_SYPKIE_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_ART_SYPKIE_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE PRZYPRAWY(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_PRZYPRAWY_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_PRZYPRAWY_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE OLEJE(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_OLEJE_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_OLEJE_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE PRZETWORY_SOSY(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_PRZETWORY_SOSY_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_PRZETWORY_SOSY_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE MAKARONY(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_MAKARONY_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_MAKARONY_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE ART_MLECZNE(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_ART_MLECZNE_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_ART_MLECZNE_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE SLODYCZE(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_SLODYCZE_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_SLODYCZE_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE NAPOJE(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_NAPOJE_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_NAPOJE_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE HERBATY_KAWY(
  PRODUKT_ID   NUMBER(6) CONSTRAINT PRODUKT_HERBATY_KAWY_FK REFERENCES PRODUKT(ID) PRIMARY KEY,
  PRODUCENT_ID NUMBER(6) CONSTRAINT PRODUCENT_HERBATY_KAWY_FK REFERENCES PRODUCENT(ID),
  NAZWA        VARCHAR2(100 CHAR),
  CENA_NETTO   NUMBER(6,2),
  VAT          NUMBER(3,2),
  STAN         NUMBER(1)
);

CREATE TABLE FAKTURA(
  ID               NUMBER(6) PRIMARY KEY,
  NUMER            VARCHAR2(9 CHAR),
  DATA_WYSTAWIENIA DATE,
  KLIENT_ID        NUMBER(6) CONSTRAINT KLIENT_FK REFERENCES KLIENT(ID),
  PRACOWNIK_ID     NUMBER(6) CONSTRAINT PRACOWNIK_FK REFERENCES PRACOWNIK(ID)
);

CREATE TABLE DANE_FAKTURY(
  ID         NUMBER(6) PRIMARY KEY,
  FAKTURA_ID NUMBER(6) CONSTRAINT FAKTURA_FK REFERENCES FAKTURA(ID),
  PRODUKT_ID NUMBER(6) CONSTRAINT PRODUKT_FK REFERENCES PRODUKT(ID)
);

CREATE TABLE SAMOCHOD(
  ID               NUMBER(6) PRIMARY KEY,
  MARKA            VARCHAR2(50 CHAR),
  MODEL            VARCHAR2(50 CHAR),
  ROCZNIK          NUMBER(4),
  NR_REJESTRACYJNY VARCHAR2(10 CHAR) NOT NULL,
  POLISA           VARCHAR2(11 CHAR) NOT NULL
);

CREATE TABLE DANE_PRACOWNIKA(
  ID                NUMBER(6) PRIMARY KEY,
  PRACOWNIK_ID      NUMBER(6) CONSTRAINT PRACOWNIK_DANE_FK REFERENCES PRACOWNIK(ID),
  SAMOCHOD_ID       NUMBER(6) CONSTRAINT SAMOCHOD_FK REFERENCES SAMOCHOD(ID),
  DATA_ZATRUDNIENIA DATE,
  STANOWISKO	      VARCHAR2(50 CHAR),         
  NR_UMOWY          NUMBER(4) NOT NULL,
  PENSJA            NUMBER(5)
);

--TABELE LOGOW - WYZWALACZE:

CREATE TABLE FAKTURA_LOG(
  ID_LOG      NUMBER,
  DATA_ZMIANY DATE,
  LOGIN_USER  VARCHAR2(30),
  OLD_NUMER   VARCHAR2(50 CHAR),
  NEW_NUMER   VARCHAR2(50 CHAR)
);

CREATE TABLE SAMOCHOD_LOG(
  ID_LOG NUMBER,
  DATA_ZMIANY DATE,
  LOGIN_USER VARCHAR2(30),
  OLD_MARKA VARCHAR2(50 CHAR),
  NEW_MARKA VARCHAR2(50 CHAR),
  OLD_MODEL VARCHAR2(50 CHAR),
  NEW_MODEL VARCHAR2(50 CHAR),
  OLD_ROCZNIK VARCHAR2(50 CHAR),
  NEW_ROCZNIK VARCHAR2(50 CHAR),
  OLD_NR_REJESTRACYJNY VARCHAR2(50 CHAR),
  NEW_NR_REJESTRACYJNY VARCHAR2(50 CHAR),
  OLD_POLISA VARCHAR2(50 CHAR),
  NEW_POLISA VARCHAR2(50 CHAR)
);

CREATE TABLE KLIENT_LOG(
  ID_LOG NUMBER,
  DATA_ZMIANY DATE,
  LOGIN_USER VARCHAR2(30),
  OLD_NAZWA VARCHAR2(50 CHAR),
  NEW_NAZWA VARCHAR2(50 CHAR),
  OLD_NIP VARCHAR2(50 CHAR),
  NEW_NIP VARCHAR2(50 CHAR)
);
SET ECHO OFF