SET ECHO ON
CREATE OR REPLACE VIEW WARTOSCI_FAKTUR AS 
  SELECT FAKTURA.ID, FAKTURA.NUMER, FAKTURA.DATA_WYSTAWIENIA,COUNT(PRODUKT.ID) AS ILOSC_PRODUKTOW, SUM(PRODUKT.CENA_NETTO) AS CENA_NETTO, 
  FAKTURA.VAT, FAKTURA.CENA_BRUTTO FROM PRODUKT,FAKTURA,DANE_FAKTURY
  WHERE PRODUKT.ID=DANE_FAKTURY.PRODUKT_ID AND DANE_FAKTURY.FAKTURA_ID=FAKTURA.ID
  GROUP BY FAKTURA.ID,FAKTURA.NUMER, FAKTURA.DATA_WYSTAWIENIA,FAKTURA.VAT, FAKTURA.CENA_BRUTTO ORDER BY FAKTURA.ID
  WITH CHECK OPTION;

CREATE OR REPLACE VIEW KLIENT_FAKTURA AS
  SELECT COUNT(FAKTURA.ID) AS FV ,KLIENT.NIP FROM FAKTURA, KLIENT
  WHERE KLIENT.ID=FAKTURA.KLIENT_ID GROUP BY KLIENT.NAZWA,KLIENT.NIP
  WITH CHECK OPTION;

CREATE OR REPLACE VIEW SAMOCHOD_PRACOWNIK AS
  SELECT PRACOWNIK_ID AS NR, PRACOWNIK.IMIE AS IMIE, PRACOWNIK.NAZWISKO AS NAZWISKO,SAMOCHOD.ID AS ID_AUTA
  FROM DANE_PRACOWNIKA
  INNER JOIN PRACOWNIK ON DANE_PRACOWNIKA.PRACOWNIK_ID = PRACOWNIK.ID
  LEFT OUTER JOIN SAMOCHOD ON DANE_PRACOWNIKA.SAMOCHOD_ID = SAMOCHOD.ID 
  ORDER BY PRACOWNIK.ID ASC;
COMMIT;
SET ECHO OFF

