$CLS
PROMPT Menu:
PROMPT 1. CREATE TABLES
PROMPT 2. CREATE SEQUENCES
PROMPT 3. INSERT INTO TABLES
PROMPT 4. CREATE VIEW
PROMPT 5. CREATE PROCEDURES
PROMPT 6. CREATE TRIGGERS
PROMPT 7. DROP TABLE
PROMPT 8. DROP SEQUENCES
PROMPT 9. DROP PROCEDURES
PROMPT A. DROP VIEW
PROMPT B. DROP TRIGGERS
PROMPT C. EXECUTE PROCEDURE
PROMPT D. SELECT FROM VIEW
PROMPT E. SELECT FROM TABLE_LOG
PROMPT F. DOWOLNA INSTRUKCJA
PROMPT 0. KONIEC
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT 'WYBIERZ OPCJE 0-F: '
$CLS
PROMPT wybor = &wybor
@&wybor\main.sql &wybor
PROMPT 
PROMPT # Wcisnij ENTER #
PAUSE
@main.sql