SET ECHO ON
DROP TABLE PRODUKT CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCENT CASCADE CONSTRAINTS PURGE;
DROP TABLE PRACOWNIK CASCADE CONSTRAINTS PURGE;
DROP TABLE KLIENT CASCADE CONSTRAINTS PURGE;
DROP TABLE ART_SYPKIE CASCADE CONSTRAINTS PURGE;
DROP TABLE PRZYPRAWY CASCADE CONSTRAINTS PURGE;
DROP TABLE OLEJE CASCADE CONSTRAINTS PURGE;
DROP TABLE PRZETWORY_SOSY CASCADE CONSTRAINTS PURGE;
DROP TABLE MAKARONY CASCADE CONSTRAINTS PURGE;
DROP TABLE ART_MLECZNE CASCADE CONSTRAINTS PURGE;
DROP TABLE SLODYCZE CASCADE CONSTRAINTS PURGE;
DROP TABLE NAPOJE CASCADE CONSTRAINTS PURGE;
DROP TABLE HERBATY_KAWY CASCADE CONSTRAINTS PURGE;
DROP TABLE FAKTURA CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMOCHOD CASCADE CONSTRAINTS PURGE;
DROP TABLE DANE_PRACOWNIKA CASCADE CONSTRAINTS PURGE;
DROP TABLE DANE_FAKTURY CASCADE CONSTRAINTS PURGE;
DROP TABLE FAKTURA_LOG CASCADE CONSTRAINTS PURGE;
DROP TABLE SAMOCHOD_LOG CASCADE CONSTRAINTS PURGE;
DROP TABLE KLIENT_LOG CASCADE CONSTRAINTS PURGE;
SET ECHO OFF
