$CLS
PROMPT Menu:
PROMPT 1. SELECT * FROM WARTOSCI_FAKTUR;;
PROMPT 2. SELECT * FROM KLIENT_FAKTURA;;
PROMPT 3. SELECT * FROM SAMOCHOD_PRACOWNIK;
ACCEPT wybor CHAR FORMAT 'A1' DEFAULT '0' PROMPT 'WYBIERZ NR OPCJI OD 1 DO 3: '
$CLS
DEFINE CURR_DIR='&1'
PROMPT wybor = &wybor
@'&CURR_DIR/&wybor.sql'
PROMPT # Wcisnij ENTER #
PAUSE
@main.sql